#!/usr/bin/env bash
set -u

DO_API_BASE=https://api.digitalocean.com/v2

# Get from DigitalOcean metadata service
DO_DROPLET_ID=$(curl -m 5 -s http://169.254.169.254/metadata/v1/id)
if [ $? -ne 0 ]; then
  echo "ERROR: could not get droplet ID from metadata service"
  exit 1
fi

curl --header "Content-Type: application/json" \
     --header "Authorization: Bearer $DO_API_KEY" \
     --data-binary "{\"type\":\"assign\",\"droplet_id\":\"$DO_DROPLET_ID\"}" \
     --request POST "$DO_API_BASE/floating_ips/$DO_FLOATING_IP/actions"
